# Generated by Django 4.2.6 on 2023-12-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
