# Generated by Django 4.2.6 on 2023-12-06 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance_request',
            name='image_url',
        ),
        migrations.AddField(
            model_name='maintenance_request',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
