# Generated by Django 4.2.6 on 2023-12-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_requests', '0002_remove_maintenance_request_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_request',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
