# Generated by Django 4.2.6 on 2023-12-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_requests', '0003_alter_maintenance_request_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_request',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='maintenance_request',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
