# Generated by Django 4.2.6 on 2023-12-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_requests', '0005_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='apartment_number',
            field=models.IntegerField(),
        ),
    ]
