# Generated by Django 4.2.6 on 2023-12-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_requests', '0006_alter_tenant_apartment_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['apartment']},
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='apartment_number',
            new_name='apartment',
        ),
    ]
