# Generated by Django 4.2.6 on 2023-12-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_requests', '0007_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance_request',
            name='area',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
